### ISSUE TITLE
Add ability to generate non-git sources

### ISSUE THREAD

**Issue by demery** [upenn-libraries/guardian_manifest#3]
https://github.com/upenn-libraries/guardian_manifest/blob/b31a5110447c5f3da3e02b28cce0b7c2cd2e1bd8/guardian_manifest.rb#L21

At present, guardian_manifest.rb always appends `.git` to the directive name. This does not work for non-git sources. Change to allow non-git source types.

**Comment by kelynch** [comment]
Addressed in #4
