### ISSUE TITLE
Miscellaneous path issues

### ISSUE THREAD

**Issue by demery** [upenn-libraries/guardian_manifest#6]
There are to path bugs:

* erroneous prefixing of `/` on gitannex_bulwark paths

This [code](https://github.com/upenn-libraries/guardian_manifest/blob/master/guardian_manifest.rb#L40) always prefixes a `/` to git paths, breaking source URIs that begin with `ssh://..`.

* need for directive name directory in `:verification_destination`

The verification destination should append  an object-specific directory for `: verification_destination`. 

When the root verification and workspace directories are the same, unzipped files can end up in the same location as the zip file:

``` yaml
:compressed_destination: /workspace/mscodex123-<UUID>/mscodex123.zip
:verification_destination: /workspace/mscodex123-<UUID>/
```

Change `:verification_destination` to the following so that unzipped files are isolated from the `.zip` file.

```
:verification_destination: /workspace/mscodex123-<UUID>/mscodex123
```

**Comment by kelynch** [comment]
Addressed in #7
